# Data Cleaning

In [13]:
import pandas as pd 
df = pd.read_csv("../Datasets/fraud_detection_elite_v3.csv")

In [6]:
df.shape

(12000, 21)

In [7]:
df.head()

,transaction_id,user_id,amount,transaction_type,merchant_category,timestamp,transaction_frequency,avg_user_amount,deviation_from_avg,transaction_gap_seconds,...,failed_attempts,device_type,location,is_foreign_transaction,unusual_amount_flag,velocity_flag,new_device_flag,location_change_flag,night_transaction_flag,is_fraud
0,T7175,U697,2223.52,transfer,electronics,2026-05-03 16:47:17.308484,8,2071.728078,151.79,2813,...,1,mobile,India,0,0,0,0,0,0,0
1,T10950,U515,1507.74,transfer,fashion,2026-05-03 16:41:02.308484,2,1603.892701,96.15,4460,...,1,mobile,UK,1,0,0,1,0,0,0
2,T3748,U978,2172.87,withdrawal,travel,2026-05-03 13:06:51.308484,10,2815.926122,643.06,2045,...,1,mobile,UK,1,0,1,0,1,0,1
3,T11845,U902,4795.42,transfer,gaming,2026-05-03 17:30:21.308484,3,2507.295598,2288.12,4326,...,2,web,Germany,1,0,0,0,0,0,0
4,T2061,U584,519.97,transfer,electronics,2026-05-03 12:33:07.308484,2,1865.386478,1345.42,4222,...,1,web,UAE,1,0,0,0,0,0,0

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   transaction_id           12000 non-null  str
 1   user_id                  12000 non-null  str
 2   amount                   12000 non-null  float64
 3   transaction_type         12000 non-null  str
 4   merchant_category        12000 non-null  str
 5   timestamp                12000 non-null  str
 6   transaction_frequency    12000 non-null  int64
 7   avg_user_amount          12000 non-null  float64
 8   deviation_from_avg       12000 non-null  float64
 9   transaction_gap_seconds  12000 non-null  int64
 10  account_age_days         12000 non-null  int64
 11  failed_attempts          12000 non-null  int64
 12  device_type              12000 non-null  str
 13  location                 12000 non-null  str
 14  is_foreign_transaction   12000 non-null  int64
 15  unusual_amount_flag      12000 non-null  int64
 16  velocity_flag            12000 non-null  int64
 17  new_device_flag          12000 non-null  int64
 18  location_change_flag     12000 non-null  int64
 19  night_transaction_flag   12000 non-null  int64
 20  is_fraud                 12000 non-null  int64
dtypes: float64(3), int64(11), str(7)
memory usage: 1.9 MB

In [20]:
df.columns

Index(['transaction_id', 'user_id', 'amount', 'transaction_type',
       'merchant_category', 'timestamp', 'transaction_frequency',
       'avg_user_amount', 'deviation_from_avg', 'transaction_gap_seconds',
       'account_age_days', 'failed_attempts', 'device_type', 'location',
       'is_foreign_transaction', 'unusual_amount_flag', 'velocity_flag',
       'new_device_flag', 'location_change_flag', 'night_transaction_flag',
       'is_fraud'],
      dtype='str')

In [18]:
df.describe()

,amount,transaction_frequency,avg_user_amount,deviation_from_avg,transaction_gap_seconds,account_age_days,failed_attempts,is_foreign_transaction,unusual_amount_flag,velocity_flag,new_device_flag,location_change_flag,night_transaction_flag,is_fraud
count,12000.000000,12000.00000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000
mean,1780.071891,5.84400,1759.194379,695.817693,2803.918833,996.186500,0.968417,0.792167,0.022583,0.248417,0.239917,0.138833,0.002583,0.038667
std,1180.807318,3.13738,714.160067,614.266176,1822.169056,574.545777,0.959425,0.405774,0.148577,0.432113,0.427050,0.345787,0.050763,0.192807
min,50.000000,1.00000,500.013842,0.100000,30.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,878.010000,3.00000,1149.762448,234.187500,1392.000000,513.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1547.080000,6.00000,1780.992279,525.245000,2668.500000,994.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2478.230000,8.00000,2365.873530,977.020000,3979.000000,1491.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,7164.120000,11.00000,2999.727655,4513.510000,9982.000000,1999.000000,7.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [14]:
df.isnull().sum()

transaction_id             0
user_id                    0
amount                     0
transaction_type           0
merchant_category          0
timestamp                  0
transaction_frequency      0
avg_user_amount            0
deviation_from_avg         0
transaction_gap_seconds    0
account_age_days           0
failed_attempts            0
device_type                0
location                   0
is_foreign_transaction     0
unusual_amount_flag        0
velocity_flag              0
new_device_flag            0
location_change_flag       0
night_transaction_flag     0
is_fraud                   0
dtype: int64

In [10]:
categorical_columns = df.select_dtypes(include=['str'])
numerical_columns = df.select_dtypes(exclude=['str'])

In [12]:
categorical_columns.head()
numerical_columns.head()

,amount,transaction_frequency,avg_user_amount,deviation_from_avg,transaction_gap_seconds,account_age_days,failed_attempts,is_foreign_transaction,unusual_amount_flag,velocity_flag,new_device_flag,location_change_flag,night_transaction_flag,is_fraud
0,2223.52,8,2071.728078,151.79,2813,794,1,0,0,0,0,0,0,0
1,1507.74,2,1603.892701,96.15,4460,1809,1,1,0,0,1,0,0,0
2,2172.87,10,2815.926122,643.06,2045,682,1,1,0,1,0,1,0,1
3,4795.42,3,2507.295598,2288.12,4326,349,2,1,0,0,0,0,0,0
4,519.97,2,1865.386478,1345.42,4222,583,1,1,0,0,0,0,0,0

In [29]:
categorical_columns

,transaction_id,user_id,transaction_type,merchant_category,timestamp,device_type,location
0,T7175,U697,transfer,electronics,2026-05-03 16:47:17.308484,mobile,India
1,T10950,U515,transfer,fashion,2026-05-03 16:41:02.308484,mobile,UK
2,T3748,U978,withdrawal,travel,2026-05-03 13:06:51.308484,mobile,UK
3,T11845,U902,transfer,gaming,2026-05-03 17:30:21.308484,web,Germany
4,T2061,U584,transfer,electronics,2026-05-03 12:33:07.308484,web,UAE
...,...,...,...,...,...,...,...
11995,T3722,U1021,withdrawal,travel,2026-05-03 11:42:48.308484,mobile,USA
11996,T3365,U1044,withdrawal,grocery,2026-05-03 12:26:49.308484,mobile,UK
11997,T3001,U671,transfer,fashion,2026-05-03 11:48:58.308484,mobile,Germany
11998,T10192,U355,payment,travel,2026-05-03 20:35:35.308484,web,Germany
11999,T1484,U153,transfer,electronics,2026-05-03 12:52:58.308484,mobile,India

In [20]:
numerical_columns
numerical_columns.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   amount                   12000 non-null  float64
 1   transaction_frequency    12000 non-null  int64
 2   avg_user_amount          12000 non-null  float64
 3   deviation_from_avg       12000 non-null  float64
 4   transaction_gap_seconds  12000 non-null  int64
 5   account_age_days         12000 non-null  int64
 6   failed_attempts          12000 non-null  int64
 7   is_foreign_transaction   12000 non-null  int64
 8   unusual_amount_flag      12000 non-null  int64
 9   velocity_flag            12000 non-null  int64
 10  new_device_flag          12000 non-null  int64
 11  location_change_flag     12000 non-null  int64
 12  night_transaction_flag   12000 non-null  int64
 13  is_fraud                 12000 non-null  int64
dtypes: float64(3), int64(11)
memory usage: 1.3 MB

In [ ]:
#IN CASE A NULL VALUE IS PRESENT.
from pandas.api.types import is_numeric_dtype
#for numerical columns, place mean values at empty records.
#for categorical columns, place modal value at  empty records.

for i in df.columns:
    if is_numeric_dtype(df[i]):
        mean = df[i].mean()
        df[i] = df[i].fillna(mean)
    else:
        mode = df[i].mode()[0]
        df[i] = df[i].fillna(mode)

# Data Analysation

In [14]:
numerical_columns.columns

Index(['amount', 'transaction_frequency', 'avg_user_amount',
       'deviation_from_avg', 'transaction_gap_seconds', 'account_age_days',
       'failed_attempts', 'is_foreign_transaction', 'unusual_amount_flag',
       'velocity_flag', 'new_device_flag', 'location_change_flag',
       'night_transaction_flag', 'is_fraud'],
      dtype='str')

In [ ]:
fraud_transactions = df['is_fraud'].sum()
print("Total fraud_transactions:", fraud_transactions)

Total fraud_transactions: 464

In [28]:
unusual_transactions = df['unusual_amount_flag'].sum()
print("Total Unusual Transaction:",unusual_transactions)

print(df[df['unusual_amount_flag'] == 1])

Total Unusual Transaction: 271
      transaction_id user_id   amount transaction_type merchant_category  \
6              T8082   U1194  6092.12          payment       electronics
42             T8662   U1042  6596.09          payment            travel
180            T3095    U723  4596.51         transfer       electronics
253           T11421    U191  4304.18          payment            gaming
304            T8800    U208  2017.18         transfer           fashion
...              ...     ...      ...              ...               ...
11852          T3739    U704  5910.67       withdrawal           grocery
11853         T11285    U196  1694.03         transfer           fashion
11857          T3118    U528  5144.59         transfer           grocery
11920          T4045    U602  1829.53       withdrawal            gaming
11924          T9538    U723  6187.67         transfer       electronics

                        timestamp  transaction_frequency  avg_user_amount  \
6      2026-05-03 13:12:25.308484                     11      2993.845915
42     2026-05-03 15:29:03.308484                      3      2967.943273
180    2026-05-03 12:44:17.308484                      9      2281.660119
253    2026-05-03 15:44:14.308484                      7      1854.206639
304    2026-05-03 13:06:46.308484                      8       984.119162
...                           ...                    ...              ...
11852  2026-05-03 11:25:45.308484                      7      2894.498979
11853  2026-05-03 18:22:49.308484                      9       649.129865
11857  2026-05-03 15:35:12.308484                      8      2540.845467
11920  2026-05-03 12:29:51.308484                     10       753.484847
11924  2026-05-03 19:05:35.308484                      2      2952.187271

       deviation_from_avg  transaction_gap_seconds  ...  failed_attempts  \
6                 3098.27                      671  ...                1
42                3628.15                     1508  ...                2
180               2314.85                     3882  ...                0
253               2449.97                     1413  ...                1
304               1033.06                     3304  ...                1
...                   ...                      ...  ...              ...
11852             3016.17                      708  ...                0
11853             1044.90                     2988  ...                0
11857             2603.74                      218  ...                1
11920             1076.05                     4041  ...                0
11924             3235.48                     3490  ...                2

       device_type location is_foreign_transaction  unusual_amount_flag  \
6              web      UAE                      1                    1
42          mobile      UAE                      1                    1
180         mobile      USA                      1                    1
253         mobile      UAE                      1                    1
304            web    India                      0                    1
...            ...      ...                    ...                  ...
11852       mobile      USA                      1                    1
11853          web      UAE                      1                    1
11857       mobile    India                      0                    1
11920          web      USA                      1                    1
11924       mobile    India                      0                    1

       velocity_flag  new_device_flag  location_change_flag  \
6                  1                1                     1
42                 0                0                     0
180                1                0                     0
253                0                0                     0
304                0                0                     1
...              ...              ...                   ...
11852              0                0                     1
11853              1                1                     0
11857              0                0                     0
11920              1                0                     0
11924              0                0                     0

       night_transaction_flag  is_fraud
6                           0         0
42                          0         0
180                         0         0
253                         0         0
304                         0         0
...                       ...       ...
11852                       0         0
11853                       0         0
11857                       0         0
11920                       0         0
11924                       0         0

[271 rows x 21 columns]

In [7]:
foreign_transaction = df['is_foreign_transaction'].sum()
print("Total Foreign Transaction:", foreign_transaction)

Total Foreign Transaction: 9506

In [14]:
failed_attempts = df['failed_attempts'].sum()
print("Total Failed attempts:", failed_attempts)

Total Failed attempts: 11621

In [ ]:
night_transactiosn = df['night_transaction_flag'].sum()
print("Night Transaction flags:", night_transactiosn)

Total Night Transaction flags: 31

In [23]:
new_device_transactions = df['new_device_flag'].sum()
print("Transaction from new devices:", new_device_transactions)

Transaction from new devices: 2879

In [25]:
unusual_amounts = df['unusual_amount_flag'].sum()
print("Accounts with unusual amounts, than the usual balance:", unusual_amounts)

Accounts with unusual amounts, than the usual balance: 271

In [26]:
# In a fraudulent transaction dataset, a velocity_flag (or velocity feature) signifies the frequency, speed, or 
# volume of transactions associated with a specific entity (card, user, IP address, or device) within a defined,
# short time frame. It is designed to catch fraudsters who attempt to maximize profit from a stolen card or
# account before it is blocked

velocity_flags = df['velocity_flag'].sum()
print("Velocity flagged transactions:", velocity_flags)

Velocity flagged transactions: 2981

In [ ]:
print(df.loc[df['unusual_amount_flag'] == 1, 'unusual_amount_flag'])

6        1
42       1
180      1
253      1
304      1
        ..
11852    1
11853    1
11857    1
11920    1
11924    1
Name: unusual_amount_flag, Length: 271, dtype: int64

In [8]:
# Exporting clean data to csv files
df.to_csv("data_v3.csv")

In [11]:
numerical_columns.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   amount                   12000 non-null  float64
 1   transaction_frequency    12000 non-null  int64
 2   avg_user_amount          12000 non-null  float64
 3   deviation_from_avg       12000 non-null  float64
 4   transaction_gap_seconds  12000 non-null  int64
 5   account_age_days         12000 non-null  int64
 6   failed_attempts          12000 non-null  int64
 7   is_foreign_transaction   12000 non-null  int64
 8   unusual_amount_flag      12000 non-null  int64
 9   velocity_flag            12000 non-null  int64
 10  new_device_flag          12000 non-null  int64
 11  location_change_flag     12000 non-null  int64
 12  night_transaction_flag   12000 non-null  int64
 13  is_fraud                 12000 non-null  int64
dtypes: float64(3), int64(11)
memory usage: 1.3 MB

In [12]:
categorical_columns.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   transaction_id     12000 non-null  str
 1   user_id            12000 non-null  str
 2   transaction_type   12000 non-null  str
 3   merchant_category  12000 non-null  str
 4   timestamp          12000 non-null  str
 5   device_type        12000 non-null  str
 6   location           12000 non-null  str
dtypes: str(7)
memory usage: 656.4 KB